name: Update Homebrew Formula

on:
  repository_dispatch:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  make_formula:
    name: Make Formula
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: make formula
        run: ./bin/make_formula.sh
      - name: commit and push
        run: |
          git config --global user.name 'Michael Kreil'
          git config --global user.email 'github@michael-kreil.de'
          if [ -n "$(git status --porcelain)" ]; then
            git add Formula
            git commit -m "update formula automatically"
            git push
          else
            echo "no changes"
          fi
        shell: bash
