name: Update Homebrew Formula

on:
  repository_dispatch:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  make_formula:
    name: Make Formula
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: ./bin/make_formula.sh
      - run: |
          git config --global user.name 'Michael Kreil'
          git config --global user.email 'github@michael-kreil.de'
          if [ $(git status --porcelain) ]; then
            git add Formula
            git commit -m "update formula automatically"
            git push
          else
            echo "no changes"
          fi
